import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;

const aboutStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    height: "80vh",
  },
  title: {
    textAlign: "center",
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 20,
    color: "#303248",
  },
  introSect: {
    // flex: 1,
    width: windowWidth,
    backgroundColor: "#edc526",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  circle: {
    height: 190,
    width: 190,
    marginBottom: -30,
    // height: 150,
    // width: 150,
    // borderRadius: 100,
    // marginTop: 20,
    // backgroundColor: "#303248",
  },
  centerDisplay: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
  },
  backArrow: { alignSelf: "center", flex: 1 },
  logo: {
    height: 60,
    alignSelf: "center",
    flex: 1,
    resizeMode: "contain",
    marginBottom: 7,
  },
  paragraph: {
    fontSize: 15,
    margin: 13,
    marginTop: 20,
  },
  link: {
    color: "blue",
    fontSize: 15,
    marginLeft: 13,
    marginBottom: 5,
  },
  imageHader: {
    justifyContent: "center",
    alignItems: "center",
  },
  welcomeHeading: {
    marginTop: 18,
    fontSize: 20,
    fontWeight: "bold",
  },
  questionHeading: { fontSize: 20, marginTop: 10, fontWeight: "bold" },
  margin: { marginHorizontal: 20, marginTop: 10 },
  feedbackHeading: {
    paddingTop: 25,
    margin: 13,
    fontWeight: "bold",
    fontSize: 17,
    color: "#303248",
  },
  feedback: {
    paddingTop: 20,
    flex: 1,
    margin: 13,
  },
  feedbackLabel: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#303248",
    margin: 13,
  },
  feedbackContainer: {
    borderWidth: 1,
    borderRadius: 10,
    flex: 1,
    marginTop: 10,
    padding: 10,
    marginBottom: 10,
    margin: 13,
  },
  feedbackInput: {
    fontSize: 15,
    color: "gray",
    paddingTop: 5,
    paddingRight: 5,
    backgroundColor: "white",
    borderRadius: 10,
  },
  feedbackBtnText: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 20,
    color: "#e8e1db",
  },
  feedbackButton: {
    backgroundColor: "#303248",
    padding: 10,
    marginTop: 12,
    borderRadius: 10,
    marginBottom: 30,
  },
  menuEntry: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 25,
    marginHorizontal: 20,
    marginRight: 50,
  },
  menuBorder: {
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    marginTop: 25,
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  menuText: {
    paddingLeft: 40,
    fontSize: 20,
    fontWeight: "bold",
    color: "#303248",
  },
});

export default aboutStyles;
