import { StyleSheet, Dimensions, PixelRatio } from "react-native";

const windowWidth = Dimensions.get("window").width;
const getFontSize = (size: number) => size / PixelRatio.getFontScale();

const aboutStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    paddingBottom: 20,
    width: "100%",
  },
  introSect: {
    width: "100%",
    backgroundColor: "#edc526",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    paddingBottom: 8,
    shadowColor: "#b89a00",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 10,
  },
  title: {
    textAlign: "center",
    fontSize: getFontSize(26),
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 20,
    color: "#303248",
    letterSpacing: 0.5,
    fontFamily: "Karla",
  },
  centerDisplay: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
  },
  backArrow: { alignSelf: "center", flex: 1 },
  logo: {
    height: 60,
    alignSelf: "center",
    flex: 1,
    resizeMode: "contain",
    marginBottom: 7,
  },

  // ── Hero card ──────────────────────────────────────────────────────────────
  heroCard: {
    backgroundColor: "#303248",
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 24,
    paddingVertical: 28,
    paddingHorizontal: 24,
    alignItems: "center",
    shadowColor: "#1a1c2e",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 8,
  },
  heroLogo: {
    height: 100,
    width: 100,
    marginBottom: 16,
  },
  heroTitle: {
    fontFamily: "Karla",
    fontSize: getFontSize(22),
    fontWeight: "800",
    color: "#edc526",
    textAlign: "center",
    letterSpacing: 0.4,
  },
  heroSubtitle: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "rgba(232, 225, 219, 0.65)",
    textAlign: "center",
    marginTop: 6,
    lineHeight: 20,
  },

  // ── Q&A cards ──────────────────────────────────────────────────────────────
  qaCard: {
    marginHorizontal: 20,
    marginTop: 36,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(48, 50, 72, 0.1)",
  },
  qaQuestion: {
    fontFamily: "Karla",
    fontSize: getFontSize(16),
    fontWeight: "700",
    color: "#303248",
    marginBottom: 8,
  },
  qaAnswer: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "rgba(48, 50, 72, 0.7)",
    lineHeight: 22,
  },
  qaAccent: {
    height: 3,
    width: 32,
    backgroundColor: "#edc526",
    borderRadius: 2,
    marginBottom: 10,
  },

  // ── Contributors card ──────────────────────────────────────────────────────
  contributorsCard: {
    marginHorizontal: 20,
    marginTop: 16,
    paddingBottom: 16,
  },
  contributorsTitle: {
    fontFamily: "Karla",
    fontSize: getFontSize(16),
    fontWeight: "700",
    color: "#303248",
    marginBottom: 10,
  },
  contributorsText: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "#303248",
    lineHeight: 22,
  },
  contributorsLabel: {
    fontFamily: "Karla",
    fontSize: getFontSize(12),
    fontWeight: "700",
    color: "rgba(48, 50, 72, 0.55)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 4,
    marginTop: 10,
  },

  // ── Body text ──────────────────────────────────────────────────────────────
  paragraph: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "rgba(48, 50, 72, 0.75)",
    lineHeight: 22,
    marginHorizontal: 20,
    marginTop: 16,
  },
  link: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "#edc526",
    fontWeight: "600",
    marginHorizontal: 20,
    marginTop: 10,
    textDecorationLine: "underline",
  },

  // ── Feedback form ─────────────────────────────────────────────────────────
  feedbackHeading: {
    fontFamily: "Karla",
    fontSize: getFontSize(18),
    fontWeight: "700",
    color: "#303248",
    // textAlign: "center",
    lineHeight: 26,
    marginBottom: 8,
  },
  feedbackCard: {
    backgroundColor: "white",
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 20,
    padding: 20,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
  },
  feedbackLabel: {
    fontFamily: "Karla",
    fontSize: getFontSize(12),
    fontWeight: "700",
    color: "rgba(48, 50, 72, 0.55)",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 10,
  },
  feedbackInput: {
    fontFamily: "Karla",
    fontSize: getFontSize(14),
    color: "#303248",
    backgroundColor: "#f5f2ef",
    borderRadius: 12,
    padding: 14,
    minHeight: 180,
    textAlignVertical: "top",
  },
  feedbackButton: {
    backgroundColor: "#303248",
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 16,
    paddingVertical: 14,
    alignItems: "center",
    shadowColor: "#1a1c2e",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 4,
  },
  feedbackBtnText: {
    fontFamily: "Karla",
    fontSize: getFontSize(15),
    fontWeight: "700",
    color: "#edc526",
    letterSpacing: 0.5,
  },

  // ── Menu card (AboutScreen) ────────────────────────────────────────────────
  menuCard: {
    backgroundColor: "white",
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 24,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 3,
    overflow: "hidden",
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 20,
    justifyContent: "space-between",
  },
  menuRowText: {
    fontFamily: "Karla",
    fontSize: getFontSize(16),
    fontWeight: "600",
    color: "#303248",
  },
  menuInternalDivider: {
    height: 1,
    backgroundColor: "rgba(48, 50, 72, 0.08)",
    marginHorizontal: 20,
  },
});

export default aboutStyles;
