import { StyleSheet } from "react-native";
const getFontSize = (size) => size;

const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
  },
  introSect: {
    flex: 1,
    backgroundColor: "#303248",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingBottom: 44,
    shadowColor: "#1a1c2e",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 14,
  },
  shadow: {
    shadowColor: "#171717",
    elevation: 20,
    position: "relative",
  },
  starredLanguagesSect: {
    flex: 1,
    paddingTop: 8,
  },
  historySect: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 12,
    paddingBottom: 16,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  savedSect: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 12,
    paddingBottom: 16,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  workbookSect: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 28,
    paddingBottom: 16,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
  },
  header: {
    paddingLeft: 24,
    paddingTop: 20,
    fontSize: getFontSize(25),
    fontWeight: "bold",
    color: "#303248",
    marginBottom: 10,
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8e1db",
  },
  noteText: {
    paddingLeft: 20,
    paddingRight: 16,
    fontSize: getFontSize(13),
    color: "#8a8699",
    textAlign: "left",
    marginBottom: 12,
    marginTop: 2,
  },
  settingsLocation: {
    marginRight: 22,
    marginTop: 20,
    marginBottom: -20,
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  settingIcon: {
    color: "rgba(232, 225, 219, 0.65)",
    fontSize: 24,
  },
  searchLocation: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginRight: 24,
    marginTop: 0,
    alignItems: "flex-end",
  },
  titleLocation: {
    flexDirection: "row",
    alignItems: "baseline",
  },
  titleText: {
    paddingLeft: 24,
    paddingTop: 44,
    fontSize: getFontSize(34),
    fontWeight: "800",
    color: "#e8e1db",
    letterSpacing: 0.3,
  },
  nameText: {
    paddingLeft: 8,
    paddingTop: 44,
    fontSize: getFontSize(34),
    fontWeight: "800",
    color: "#edc526",
    letterSpacing: 0.3,
  },
  subTitleText: {
    paddingLeft: 24,
    fontSize: getFontSize(15),
    color: "rgba(232, 225, 219, 0.6)",
    marginTop: 6,
    letterSpacing: 0.2,
  },
  iconDivider: {
    justifyContent: "flex-end",
    paddingBottom: 6,
  },
  searchIcon: {
    color: "#edc526",
    fontSize: 28,
    marginBottom: 8,
  },
  starredLangText: {
    paddingLeft: 24,
    paddingTop: 24,
    fontSize: getFontSize(22),
    fontWeight: "700",
    color: "#303248",
    letterSpacing: 0.2,
  },
  langList: {
    marginHorizontal: 16,
    marginTop: 10,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 3,
    paddingHorizontal: 12,
    paddingBottom: 12,
    marginBottom: 12,
  },
  moreLangBtn: {
    flexDirection: "row",
    marginTop: 12,
    marginLeft: 4,
    alignItems: "center",
    alignSelf: "flex-start",
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: "rgba(48, 50, 72, 0.08)",
  },
  moreLangTxt: {
    fontSize: getFontSize(13),
    fontWeight: "600",
    marginRight: 8,
    color: "#303248",
  },
  hzScroll: {
    marginRight: 16,
    marginLeft: 16,
    paddingBottom: 4,
  },
  noResultsText: {
    fontSize: getFontSize(14),
    textAlign: "center",
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
    color: "#b0adb8",
    paddingVertical: 20,
    fontStyle: "italic",
  },
  addToBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingRight: 16,
  },
  sectionTitle: {
    paddingLeft: 20,
    paddingTop: 20,
    fontSize: getFontSize(22),
    fontWeight: "700",
    color: "#303248",
    marginBottom: 4,
    letterSpacing: 0.2,
  },
  addBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: "#303248",
    marginTop: 16,
  },
  addIcon: { marginRight: 6, color: "#303248", fontSize: 13 },
  addTxt: {
    fontSize: getFontSize(13),
    color: "#303248",
    fontWeight: "600",
  },
});

export default homeStyles;
