import { StyleSheet } from "react-native";
import { ThemeColors } from "./themes";

const getFontSize = (size) => size;

const getHomeStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
    },
    introSect: {
      flex: 1,
      borderBottomLeftRadius: 30,
      borderBottomRightRadius: 30,
      paddingBottom: 44,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 14,
    },
    shadow: {
      // shadowColor: colors.shadow,
      elevation: 20,
      position: "relative",
    },
    starredLanguagesSect: {
      flex: 1,
      paddingTop: 8,
    },

    historySect: {
      flex: 1,
      backgroundColor: colors.backgroundColor,
      borderRadius: 20,
      marginHorizontal: 16,
      marginTop: 8,
      marginBottom: colors.marginBottom,
      paddingBottom: 16,
      borderWidth: colors.borderWidth,
      borderColor: colors.borderColor,
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    savedSect: {
      flex: 1,
      borderRadius: 20,
      marginHorizontal: 16,
      marginBottom: 32,
      paddingBottom: 16,
      borderWidth: 1,
      borderColor: colors.borderColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
    },
    workbookSect: {
      flex: 1,
      backgroundColor: "#ffffff",
      borderRadius: 20,
      marginHorizontal: 16,
      marginBottom: colors.marginBottom,
      paddingBottom: 16,
      borderWidth: 1,
      borderColor: "#303248",
      shadowColor: colors.shadowColor,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      fontWeight: "bold",
      color: "#303248",
      fontFamily: "Karla",
    },
    header: {
      paddingLeft: 24,
      paddingTop: 20,
      fontSize: getFontSize(25),
      fontWeight: "bold",
      marginBottom: 10,
      fontFamily: "Karla",
    },
    loading: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    noteText: {
      paddingLeft: 20,
      paddingRight: 16,
      fontSize: getFontSize(13),
      textAlign: "left",
      marginBottom: 12,
      marginTop: 2,
      fontFamily: "Karla",
    },
    settingsLocation: {
      marginRight: 22,
      marginTop: 20,
      marginBottom: -20,
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    settingIcon: {
      fontSize: 24,
    },
    searchLocation: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginRight: 24,
      marginTop: 0,
      alignItems: "flex-end",
    },
    titleLocation: {
      flexDirection: "row",
      alignItems: "baseline",
    },
    titleText: {
      paddingLeft: 24,
      paddingTop: 44,
      fontSize: getFontSize(34),
      fontWeight: "800",
      letterSpacing: 0.3,
      fontFamily: "Karla",
    },
    nameText: {
      paddingLeft: 8,
      paddingTop: 44,
      fontSize: getFontSize(34),
      fontWeight: "800",
      letterSpacing: 0.3,
      fontFamily: "Karla",
    },
    subTitleText: {
      paddingLeft: 24,
      fontSize: getFontSize(15),
      marginTop: 6,
      letterSpacing: 0.2,
      fontFamily: "Karla",
    },
    iconDivider: {
      justifyContent: "flex-end",
      paddingBottom: 6,
    },
    searchIcon: {
      fontSize: 28,
      marginBottom: 8,
    },
    starredLangText: {
      paddingLeft: 20,
      paddingTop: 24,
      fontSize: getFontSize(22),
      fontWeight: "700",
      letterSpacing: 0.2,
      fontFamily: "Karla",
    },
    langList: {
      marginHorizontal: 16,
      marginTop: 10,
      borderRadius: 16,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 3,
      paddingHorizontal: 12,
      paddingBottom: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.borderColor,
    },
    moreLangBtn: {
      flexDirection: "row",
      marginTop: 12,
      marginLeft: 4,
      alignItems: "center",
      alignSelf: "flex-start",
      paddingVertical: 7,
      paddingHorizontal: 14,
      borderRadius: 20,
    },
    moreLangTxt: {
      fontSize: getFontSize(13),
      fontWeight: "600",
      marginRight: 8,
      fontFamily: "Karla",
    },
    hzScroll: {
      marginRight: 16,
      marginLeft: 16,
      paddingBottom: 4,
    },
    noResultsText: {
      fontSize: getFontSize(14),
      textAlign: "center",
      width: "90%",
      marginLeft: "auto",
      marginRight: "auto",
      paddingVertical: 20,
      fontStyle: "italic",
      fontFamily: "Karla",
    },
    addToBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingRight: 16,
    },
    sectionTitle: {
      paddingLeft: 20,
      paddingTop: 20,
      fontSize: getFontSize(22),
      fontWeight: "700",
      marginBottom: 4,
      letterSpacing: 0.2,
      fontFamily: "Karla",
    },
    addBtn: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: colors.borderColor,
      marginTop: 16,
    },
    addIcon: { marginRight: 6,  fontSize: 13 },
    addTxt: {
      fontSize: getFontSize(13),
      fontWeight: "600",
      fontFamily: "Karla",
    },
  });

export default getHomeStyles;
