import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;

const playlistStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    height: "80vh",
  },
  button: {
    backgroundColor: "#303248",
    marginVertical: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 10,
    marginLeft: "auto",
    marginRight: "auto",
    width: "80%",
  },
  buttonText: {
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
    color: "#edc525",
  },
  playlistCardName: {
    fontSize: 13,
    fontWeight: "500",
    color: "black",
    marginTop: 10,
    width: 130,
  },
  playlistCardImage: {
    width: 130,
    height: 130,
    borderRadius: 5,
    backgroundColor: "white",
    elevation: 8,
  },
  playlistItemEntry: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 30,
    marginVertical: 7,
  },
  playlistImageContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  playlistItemImage: {
    width: 50,
    height: 50,
    borderRadius: 5,
  },
  playlistItemName: {
    fontWeight: "bold",
    fontSize: 14,
    maxWidth: 190,
  },
  playlistItemArtist: {
    maxWidth: 190,
    color: "grey",
  },
  playlistItemLike: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "30%",
    alignItems: "center",
  },
  playlistLikeIcon: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 5,
  },
  playlistItemBorder: {
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    marginHorizontal: 30,
  },
  addToPlaylistHeader: {
    backgroundColor: "#5bc8a6",
    paddingTop: 20,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    paddingBottom: 15,
    paddingLeft: 20,
  },
  addToPlaylistTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    marginTop: 20,
  },
  addToPlaylistDropdown: {
    marginLeft: 20,
    paddingTop: 30,
    width: "15%",
    justifyContent: "center",
    alignSelf: "center",
    flexDirection: "row",
    zIndex: 10000,
  },
  title: {
    textAlign: "left",
    fontSize: 35,
    fontWeight: "800",
    marginLeft: 20,
    paddingTop: 15,
    color: "white",
  },
  introSect: {
    flex: 1,
    width: windowWidth,
    backgroundColor: "#303248",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderRadius: 15,
    paddingBottom: 30,
  },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    marginHorizontal: 20,
    paddingHorizontal: 15,
    marginTop: 20,
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    color: "#000",
    paddingHorizontal: 10,
  },
  loading: {
    marginTop: 50,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8e1db",
  },
  background: { backgroundColor: "#e8e1db", flex: 1, height: "80vh" },
  header: {
    paddingTop: 30,
    backgroundColor: "#ECC516",
    paddingBottom: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  arrowLocation: { marginLeft: 20 },
  controlsLocation: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginRight: 20,
  },
  playLocation: { flexDirection: "row", alignItems: "center" },
  playBtn: { fontSize: 35, marginRight: 20 },
  descLocation: { marginHorizontal: 20, marginVertical: 10 },
  descTitle: { fontSize: 18, paddingBottom: 5, color: "gray" },
  descTxtLocation: {
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 15,
  },
  colTitles: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 30,
    paddingTop: 15,
    marginRight: 40,
  },
  colLocation: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "30%",
    alignItems: "center",
  },
  colText: { color: "gray" },
  noResults: {
    textAlign: "left",
    paddingBottom: 240,
    color: "gray",
    fontSize: 15,
    fontWeight: "bold",
    paddingLeft: 30,
    paddingRight: 30,
  },
  addSongBtn: {
    flexDirection: "row",
    marginLeft: 35,
    alignItems: "center",
    paddingTop: 15,
    marginBottom: 20,
  },
  addSongIcon: { marginRight: 5 },
  addSongTxt: { fontSize: 20, color: "gray" },
});

export default playlistStyles;
