import { StyleSheet, PixelRatio } from "react-native";
const fontScale = PixelRatio.getFontScale();
const getFontSize = (size: number) => size / fontScale;

const searchStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    height: "91vh",
  },
  blueSection: {
    backgroundColor: "#303248",
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  backButton: {
    marginRight: 12,
    padding: 4,
  },
  searchBar: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.08)",
  },
  searchInput: {
    flex: 1,
    color: "#e8e1db",
    paddingHorizontal: 8,
    fontSize: getFontSize(15),
  },
  noteAndButtonContainer: {
    marginHorizontal: 20,
    marginTop: 16,
    marginBottom: 4,
    flexDirection: "row",
    alignItems: "center",
  },
  languageButton: {
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: "#edc526",
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 18,
  },
  buttonText: {
    fontWeight: "700",
    color: "#edc526",
    fontSize: getFontSize(13),
    letterSpacing: 0.5,
  },
  sectionHeader: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  sectionLabel: {
    fontSize: getFontSize(13),
    fontWeight: "700",
    color: "#edc526",
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  sectionLabelLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(48, 50, 72, 0.15)",
    marginLeft: 12,
  },
  flatListContainer: {
    paddingHorizontal: 12,
    paddingBottom: 20,
  },
  placeholderTxt: {
    paddingHorizontal: 24,
    paddingTop: 8,
    color: "rgba(48, 50, 72, 0.45)",
    fontSize: getFontSize(14),
    fontStyle: "italic",
  },
  emptyState: {
    alignItems: "center",
    paddingTop: 60,
    paddingHorizontal: 40,
  },
  emptyStateText: {
    fontSize: getFontSize(15),
    color: "rgba(48, 50, 72, 0.4)",
    textAlign: "center",
    marginTop: 12,
  },
  // Language screen
  languagesTitle: {
    fontSize: getFontSize(13),
    fontWeight: "700",
    color: "#edc526",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginTop: 20,
    marginBottom: 16,
    paddingHorizontal: 24,
  },
  languagesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 20,
  },
  languageItem: {
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: 16,
    padding: 12,
    marginBottom: 16,
    shadowColor: "#303248",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
  },
  playlistImage: {
    width: 150,
    height: 100,
    borderRadius: 10,
    marginBottom: 8,
  },
  languageText: {
    fontWeight: "700",
    fontSize: getFontSize(14),
    color: "#303248",
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8e1db",
  },
  // Kept for compatibility
  space: { height: 0 },
  noSearchTxt: { flex: 1, backgroundColor: "#e8e1db" },
  searchResultItem: { flex: 1, margin: 5, alignItems: "center" },
  albumContainer: { alignItems: "center" },
  coverImage: { width: 120, height: 120, borderRadius: 10 },
  title: { fontWeight: "bold", fontSize: 14, color: "black", textAlign: "center", marginTop: 5 },
  artist: { color: "#989898", textAlign: "center" },
  noteText: { marginBottom: 10, marginLeft: 10 },
});

export default searchStyles;
