import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;

const settingStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    height: "91vh",
  },
  title: {
    textAlign: "center",
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 20,
    color: "#e8e1db",
  },
  introSect: {
    // flex: 1,
    width: windowWidth,
    backgroundColor: "#303248",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  circle: {
    height: 150,
    width: 150,
    borderRadius: 100,
    marginTop: 20,
    backgroundColor: "#303248",
  },
  centerDisplay: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 30,
    marginLeft: 20,
    marginRight: 20,
  },
  backArrow: { alignSelf: "center", flex: 1 },
  logo: {
    height: 60,
    alignSelf: "center",
    flex: 1,
    resizeMode: "contain",
    marginBottom: 7,
  },
  settingTitle: {
    fontSize: 25,
    fontWeight: "bold",
    marginHorizontal: 20,
    marginTop: 20,
    color: "#ff4a2a",
  },
  settingText: {
    fontSize: 20,
    color: "gray",
  },
  settingRow: {
    flexDirection: "row",
    marginHorizontal: 10,
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 10,
  },
  border: {
    borderRadius: 10,
    borderWidth: 2,
    marginHorizontal: 10,
    borderColor: "gray",
    paddingVertical: 10,
  },
  divider: {
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    paddingTop: 10,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  deleteButtonText: {
    marginVertical: 10,
    textAlign: "center",
    backgroundColor: "#ff4a2a",
    fontSize: 25,
    fontWeight: "bold",
    color: "#e8e1db",
    marginHorizontal: 30,
    borderRadius: 20,
  },
  deleteButton: {
    marginHorizontal: 50,
    borderRadius: 20,
    backgroundColor: "#ff4a2a",
    marginTop: 20,
  },
  settingsButton: {
    backgroundColor: "#ff4a2a",
    borderRadius: 10,
    marginTop: 5,
    marginBottom: 30,
    width: "80%",
  },
  settingsBtnText: {
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    color: "#e8e1db",
    marginVertical: 3,
  },
  btnContainer: {
    justifyContent: "center",
    alignItems: "center",
  },
  alertText: {
    marginHorizontal: 20,
    color: "#ff4a2a",
    marginBottom: 10,
  },
  currentTxt: {
    fontSize: 20,
    color: "#303248",
    fontWeight: "bold",
  },
  zIndexValue: {
    zIndex: 10000,
  },
  logOut: {
    borderRadius: 15,
    overflow: "hidden",
    marginTop: 20,
    textAlign: "center",
    backgroundColor: "#ff4a2a",
    fontSize: 25,
    fontWeight: "bold",
    color: "#e8e1db",
    marginHorizontal: 100,
  },
  menuDivider: {
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    marginTop: 25,
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  viewProfile: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: "auto",
    marginLeft: "auto",
    marginTop: 30,
  },
  viewProfileTitle: {
    marginLeft: 30,
    justifyContent: "center",
    alignItems: "center",
  },
  usernameText: { fontSize: 20, fontWeight: "bold", color: "#303248" },
  profileSubtitle: {
    color: "gray",
    marginTop: 2,
  },
  menuOptions: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: "auto",
    marginLeft: "auto",
    marginTop: 25,
  },
  menuOptionsTxt: {
    marginLeft: 25,
    fontSize: 20,
    fontWeight: "bold",
    color: "#303248",
  },
});

export default settingStyles;
