import { PixelRatio, StyleSheet } from "react-native";

const fontScale = PixelRatio.getFontScale();
const getFontSize = (size) => size / fontScale;

const wordStyles = StyleSheet.create({
  word: {
    marginBottom: 2,
    fontSize: getFontSize(15),
    fontWeight: "600",
    color: "#303248",
  },
  translation: {
    marginLeft: 0,
    fontSize: getFontSize(13),
    color: "rgba(48, 50, 72, 0.5)",
  },
  modalbg: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.6)",
  },
  modalforefront: {
    backgroundColor: "#303248",
    padding: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    minWidth: 320,
  },
  modalTextBackground: {
    backgroundColor: "rgba(255,255,255,0.05)",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 16,
  },
  modalText: {
    color: "white",
    fontSize: getFontSize(18),
    flexDirection: "row",
    alignItems: "baseline",
    marginBottom: 6,
  },
  originalLabel: {
    fontStyle: "italic",
    fontSize: getFontSize(14),
    color: "rgba(232, 225, 219, 0.55)",
    marginRight: 6,
  },
  originalText: {
    fontWeight: "700",
    fontSize: getFontSize(28),
    color: "#e8e1db",
  },
  prefLabel: {
    fontStyle: "italic",
    fontSize: getFontSize(14),
    color: "rgba(232, 225, 219, 0.55)",
    marginRight: 6,
  },
  prefText: {
    fontWeight: "700",
    fontSize: getFontSize(24),
    color: "#edc526",
  },
  dictate: {
    fontSize: getFontSize(11),
    color: "rgba(232, 225, 219, 0.4)",
    marginTop: 8,
  },
  definition: {
    fontSize: getFontSize(15),
    color: "rgba(232, 225, 219, 0.8)",
    marginBottom: 4,
  },
  pos: {
    fontSize: getFontSize(13),
    color: "rgba(232, 225, 219, 0.4)",
    fontStyle: "italic",
  },
  closeModal: {},
  saveWordModal: {},
  modalButtons: {
    color: "#303248",
    fontWeight: "700",
    fontSize: getFontSize(15),
    marginHorizontal: 5,
  },
  modalButtonsClose: {
    color: "#e8e1db",
    fontWeight: "600",
    fontSize: getFontSize(15),
    marginHorizontal: 5,
  },
  dropdown: {
    textAlign: "center",
    paddingLeft: 10,
    height: 35,
    width: 325,
    borderColor: "rgba(255, 255, 255, 0.15)",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 8,
    color: "white",
    zIndex: 100000,
  },
  placeholderStyle: {
    fontSize: getFontSize(16),
    color: "white",
  },
  selectedTextStyle: {
    fontSize: getFontSize(16),
    color: "white",
  },
  iconStyle: {
    width: 20,
    height: 20,
    color: "white",
  },
  newWorkbookInput: {
    borderWidth: 1,
    padding: 8,
    paddingLeft: 10,
    borderRadius: 8,
    borderColor: "rgba(255,255,255,0.15)",
    marginTop: 10,
    marginHorizontal: 2,
    color: "white",
    fontSize: getFontSize(14),
  },
  closeButton: {
    backgroundColor: "rgba(255,255,255,0.1)",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.15)",
  },
  saveButton: {
    backgroundColor: "#edc526",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  container: {
    flex: 1,
    backgroundColor: "#e8e1db",
    height: "91vh",
  },
  title: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    marginTop: 20,
  },
  inputContainer: {
    flexDirection: "row",
    marginVertical: 10,
    marginLeft: "auto",
    marginRight: "auto",
    width: "90%",
    alignItems: "center",
  },
  inputWrapper: {
    flex: 1,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 0.5,
    paddingVertical: 5,
    marginBottom: 10,
  },
  icon: {
    marginRight: 10,
  },
  input: {
    fontSize: 18,
    flex: 1,
    marginLeft: 8,
  },
  wordInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderBottomWidth: 0.5,
    marginBottom: 20,
    marginLeft: "auto",
    marginRight: "auto",
    width: "90%",
  },
  button: {
    backgroundColor: "#303248",
    marginVertical: 6,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 20,
    borderRadius: 10,
    marginLeft: "auto",
    marginRight: "auto",
    width: "80%",
  },
  buttonText: {
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
    color: "#edc525",
  },
  header: {
    backgroundColor: "#303248",
    paddingTop: 45,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingBottom: 15,
    paddingLeft: 20,
  },
  bookNameLocation: { flexDirection: "row", marginLeft: 20, paddingTop: 10 },
  bookNameTitle: { fontSize: 18, fontWeight: "bold", color: "gray" },
  bookNameTxt: {
    fontSize: 18,
    marginLeft: 3,
    fontWeight: "bold",
    color: "gray",
  },
});

export default wordStyles;
