import { StyleSheet, Dimensions } from "react-native";
const windowWidth = Dimensions.get("window").width;

const workbookStyles = StyleSheet.create({
  icon: {
    elevation: 8,
    fontSize: 75,
  },
  name: {
    fontSize: 13,
    fontWeight: "500",
    color: "black",
    marginTop: 10,
    width: 80,
  },
  title: {
    textAlign: "left",
    fontSize: 35,
    fontWeight: "800",
    marginLeft: 20,
    paddingTop: 15,
    color: "white",
  },
  introSect: {
    flex: 1,
    width: windowWidth,
    backgroundColor: "#303248",
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    borderRadius: 15,
    paddingBottom: 30,
  },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 20,
    marginHorizontal: 20,
    paddingHorizontal: 15,
    marginTop: 30,
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    color: "#000",
    paddingHorizontal: 10,
  },
  loading: {
    marginTop: 50,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#e8e1db",
  },
  button: {
    backgroundColor: "#303248",
    paddingHorizontal: 20,
    paddingVertical: 10,
    // marginTop: 60,
    marginTop: 20,
    borderRadius: 10,
    marginLeft: "auto",
    marginRight: "auto",
    width: "80%",
    marginBottom: 20,
  },
  buttonText: {
    fontWeight: "bold",
    textAlign: "center",
    fontSize: 20,
    color: "#edc525",
  },
  background: { backgroundColor: "#e8e1db", flex: 1, height: "91vh" },
  header: {
    paddingTop: 50,
    backgroundColor: "#5bc8a6",
    paddingBottom: 15,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
    flexDirection: "column",
    justifyContent: "space-between",
  },
  close: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginRight: 20,
    flex: 0,
  },
  closeLocation: { flexDirection: "row", alignItems: "center" },
  closeBtn: { color: "#ff4a2a" },
  arrowBtn: { marginTop: 25, marginLeft: 20 },
  descLocation: { marginHorizontal: 20, marginVertical: 10 },
  descTitle: { fontSize: 18, paddingBottom: 3, color: "gray" },
  descTxt: {
    marginVertical: 10,
    fontSize: 18,
    marginRight: 20,
    marginLeft: 8,
  },
  descIcon: {
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 15,
  },
  wordCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginHorizontal: 30,
    paddingTop: 15,
    marginRight: 40,
  },
  wordColTxt: { color: "gray", marginLeft: 5 },
  starredCol: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "30%",
    alignItems: "center",
  },
  starredColTxt: { color: "gray", marginRight: 30 },
  deleteColTxt: { color: "gray" },
  wordList: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 30,
    marginVertical: 5,
  },
  iconCols: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "30%",
    alignItems: "center",
  },
  starIconFilled: { fontSize: 30, color: "#edc526" },
  starIconOutline: { fontSize: 30 },
  deleteIcon: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 5,
  },
  divider: {
    borderBottomColor: "gray",
    borderBottomWidth: 0.5,
    marginHorizontal: 30,
  },
  noWordsTxt: {
    textAlign: "left",
    paddingTop: 40,
    color: "gray",
    fontSize: 15,
    fontWeight: "bold",
    paddingLeft: 20,
    paddingRight: 20,
  },
  addNewWordBtn: {
    flexDirection: "row",
    marginLeft: 35,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 20,
  },
  addBtnIcon: { marginRight: 9 },
  addNewWordTxt: { fontSize: 20, color: "gray" },
});

export default workbookStyles;
